name: Contentful Migration Example

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - "**"

jobs:
  build:

    runs-on: ubuntu-latest
    name: Contentful Migration Example
    steps:
    - name: Check out code into the directory
      uses: actions/checkout@v1

    - name: Contentful Migration
      id: migrate
      uses: ./
      with:
        delete_feature: true
        set_alias: false
        master_pattern: "prod-[DD].[MM].[YYYY]-[hh][mm][ss]"
        feature_pattern: "sandbox-[branch]"
        version_field: version
        version_content_type: versionTracking
        migrations_dir: test-migrations
        space_id: ${{ secrets.SPACE_ID }}
        management_api_key: ${{ secrets.MANAGEMENT_API_KEY }}
      env:
        LOG_LEVEL: verbose


    - name: Create commit comment
      uses: peter-evans/commit-comment@v1
      with:
        body: |
          See changes to the [${{steps.migrate.outputs.environment_name }} ][1] Environment on Contentful.

          [1]: ${{steps.migrate.outputs.environment_url}}
